WITH TBPRECO AS (SELECT TBPCODIGO FROM TABPRECO 
                                 WHERE TBPSITUACAO='A'
                                  AND (TBPDTVALIDADE=NULL OR TBPDTVALIDADE>='TODAY') AND TBPTABCOMB='S'),
                                  
    CLITB AS (SELECT DISTINCT C.TBPCODIGO,CLICODIGO FROM CLITBPCOMB C
                  INNER JOIN TBPRECO  T ON C.TBPCODIGO=T.TBPCODIGO),                              
                                  
PROD AS (SELECT DISTINCT PROCODIGO2 FROM PRODU WHERE PROCODIGO2='LA0182'), 

PRECOA AS (SELECT PROCODIGO,PREPCOVENDA2 FROM PREMP WHERE EMPCODIGO=1),

 PRECOB AS (SELECT PROCODIGO,PREPCOVENDA2 FROM PREMP WHERE EMPCODIGO=1)


SELECT
CLICODIGO,
 TBP.TBPCODIGO,
  PROCODIGOA,
   CCINDICEPROA,
    CCINDICEPROA2,
    ROUND(PRCA.PREPCOVENDA2*(1-CCINDICEPROA2*1.00/100),2) VALOR_LENTE,
     CCPCOVENDAPROA,
      CCPCOVENDAPROA2,
     
       PROCODIGOB,
        CCINDICEPROB,
         CCINDICEPROB2,
          ROUND(PRCB.PREPCOVENDA2*(1-CCINDICEPROB2*1.00/100),2) VALOR_SERVICO,
           CCPCOVENDAPROB,
            CCPCOVENDAPROB2,
             ROUND(PRCA.PREPCOVENDA2*(1-CCINDICEPROA2*1.00/100),2)*2+ROUND(PRCB.PREPCOVENDA2*(1-CCINDICEPROB2*1.00/100),2) TOTAL



FROM TBPCOMBPROPRO TBP
              INNER JOIN PROD P ON P.PROCODIGO2=TBP.PROCODIGOA
               
                LEFT JOIN PRECOA PRCA ON PRCA.PROCODIGO=TBP.PROCODIGOA
                 
                 LEFT JOIN PRECOB PRCB ON PRCB.PROCODIGO=TBP.PROCODIGOB
                 
                  INNER JOIN CLITB CT ON TBP.TBPCODIGO=CT.TBPCODIGO

                  
                 
