WITH TBPRECO AS (SELECT TBPCODIGO FROM TABPRECO 
                                 WHERE TBPSITUACAO='A'
                                  AND (TBPDTVALIDADE IS NULL OR TBPDTVALIDADE>='TODAY') AND TBPTABCOMB='N'),
 
 PRECO AS (SELECT PROCODIGO,PREPCOVENDA2 FROM PREMP WHERE EMPCODIGO=1),
                                  
    CLITB AS (SELECT DISTINCT C.TBPCODIGO,CLICODIGO FROM CLITBP C
                  INNER JOIN TBPRECO  T ON C.TBPCODIGO=T.TBPCODIGO),                              
                                  
PROD AS (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO='MOVS'),
    

TAB AS(     
     SELECT C.CLICODIGO,
        T.TBPCODIGO TBPCODIGO_MONT,
         T.PROCODIGO PROCODIGO_MONT,
          TBPPCDESCTO2 DESCTO_MONT,
           TBPPCOVENDA2 VALOR_MONT1
             FROM TBPPRODU T
 LEFT JOIN PRECO PC ON PC.PROCODIGO=T.PROCODIGO
  INNER JOIN PROD P ON T.PROCODIGO=P.PROCODIGO
   INNER JOIN TBPRECO  TP ON T.TBPCODIGO=TP.TBPCODIGO
    INNER JOIN CLITB C ON T.TBPCODIGO=C.TBPCODIGO)
    
SELECT * FROM TAB WHERE
 VALOR_MONT1 IS NOT NULL