
WITH PRECO AS (SELECT PROCODIGO,PREPCOVENDA2 FROM PREMP WHERE EMPCODIGO=1)

SELECT PR.PROCODIGO PROCODIGO_MONT,
          PREPCOVENDA2 PRECO_MONT 
           FROM PRODU PR
           INNER JOIN PRECO PC ON PC.PROCODIGO=PR.PROCODIGO
           WHERE PR.PROCODIGO='MOVS'
