WITH CLI AS (SELECT * FROM PCTCLI WHERE PCTSITUACAO<>'C'),

PCT AS (
SELECT CLICODIGO,
        PCTDTFIM,
         PCTDTSUSP
         ,P.* FROM PCTPRO P
         INNER JOIN CLI C ON P.PCTNUMERO=C.PCTNUMERO
          WHERE PROCODIGO='LA0182')
          
          
SELECT * FROM PCT
 WHERE PCPSALDO>0 AND PCTDTFIM>='TODAY'