WITH CLI AS (SELECT * FROM PCTCLI WHERE PCTSITUACAO<>'C'),

PCT AS (
       SELECT CLICODIGO,
        PCTDTFIM,
         PCTDTSUSP
         ,P.* FROM PCTPRO P
          INNER JOIN CLI C ON P.PCTNUMERO=C.PCTNUMERO
           WHERE PROCODIGO='LA0182'),

PCT1 AS (  
      SELECT DISTINCT 
        CLICODIGO,
         MIN(PCPSALDO) SALDO 
          FROM PCT
           WHERE PCTDTFIM>='TODAY' AND PCPSALDO>0
            GROUP BY 1)
            
      SELECT DISTINCT 
        P.CLICODIGO,
         PCTNUMERO,
          PCPPCOUNIT,
          SALDO 
          FROM PCT P
           INNER JOIN PCT1 P1 ON P1.SALDO=P.PCPSALDO AND P.CLICODIGO=P1.CLICODIGO
           WHERE PCTDTFIM>='TODAY' AND PCPSALDO>0
            GROUP BY 1,2,3,4
            

