WITH TBPRECO AS (SELECT TBPCODIGO FROM TABPRECO 
                                 WHERE TBPSITUACAO='A'
                                  AND (TBPDTVALIDADE=NULL OR TBPDTVALIDADE>='TODAY')),
                                  
TABPROMO AS (SELECT TBPCODIGO FROM TABPRECO WHERE TBPCODIGO=1642), 

 TABPROD AS (SELECT DISTINCT PROCODIGO FROM TBPPRODU T
                                  INNER JOIN TABPROMO TP ON T.TBPCODIGO=TP.TBPCODIGO
                                   WHERE PROCODIGO='LA0182'),
 
 PRECO AS (SELECT PROCODIGO,PREPCOVENDA2 FROM PREMP WHERE EMPCODIGO=1),
                                  
    CLITB AS (SELECT DISTINCT C.TBPCODIGO,C.CLICODIGO FROM CLITBP C
                  INNER JOIN TBPRECO  T ON C.TBPCODIGO=T.TBPCODIGO),
                                  
TAB AS (SELECT C.CLICODIGO,
         T.PROCODIGO,
          MAX(TBPPCDESCTO2)MXDESCTO
  FROM TBPPRODU T
   LEFT JOIN PRECO PC ON PC.PROCODIGO=T.PROCODIGO
    INNER JOIN TABPROD TP ON T.PROCODIGO=TP.PROCODIGO
      INNER JOIN CLITB C ON T.TBPCODIGO=C.TBPCODIGO
       GROUP BY 1,2)
      
SELECT C.CLICODIGO,
         T.PROCODIGO PROCODIGO_TAB,
           TBPPCDESCTO2,
            ROUND(PREPCOVENDA2*(1-TBPPCDESCTO2*1.00/100),2)*2 VALOR_LENTE
  FROM TBPPRODU T
   LEFT JOIN PRECO PC ON PC.PROCODIGO=T.PROCODIGO
    INNER JOIN TABPROD TP ON T.PROCODIGO=TP.PROCODIGO
      INNER JOIN CLITB C ON T.TBPCODIGO=C.TBPCODIGO
       INNER JOIN TAB TA ON TA.CLICODIGO=C.CLICODIGO AND T.TBPPCDESCTO2=TA.MXDESCTO
       
       
       
       
       
       